import 'package:flutter_dotenv/flutter_dotenv.dart' as DotEnv;
import 'package:flutter_dotenv/flutter_dotenv.dart';

class LabelTexts {
  static List texts = [
    //Drawer items
    'Dashboard',
    'Activation Codes',
    'Activation Code',
    'E Library',
    "You have not access",
    "No E Library Tutorial Found",
    'Dream List',
    'Guest List',
    'Invitation Script',
    'Meeting',
    'Notes',
    'Activity',
    'My Analytics',
    'Team',
    'My Team',
    'Team Request List',
    'Team Analytics',
    'Team Activity',
    'Team Dream',
    'Badge Achiever',
    'Badge',
    'My Badge',
    'Request for Badge',
    'View Request',
    'History',
    'Broadcast',
    'My Broadcast',
    'My Broadcast Message',
    'Team Broadcast',
    'News',
    'Gallery',
    'Inspiration Club',
    // dotenv.env['VESTIGE_NAME'],
    dotenv.env['VESTIGE_NAME'],
    'Testimonials',
    'FAQs',
    'Feedback',
    'Contact Us',
    'App Language',
    'Share',

    //home
    'Activity',
    'My Analytics',
    'Upgrade Package',
    'Video',
    'Audio',
    'PDF',
    dotenv.env['PRODUCT_NAME'],
    'Profile',
    'Personal Performance',
    'New Guests',
    'Invited',
    'Presentation',
    'Followup',
    'Closed',
    'Not Interested',
    'Guest',
    'Follow Ups',
    'Close',
    'Not Interested',
    'Team Performance',
    'Notes',
    'Click here to create your business notes',
    'My Activity',
    'Personal Activity circle',
    'Invitation Script',
    'Learning',
    'Top picks for you',

    // Activation code
    'Redeem Code',
    'No Activation code Found',
    'No data found',
    'Unused',
    'Used',
    'Activation Code Copied',
    'Retry',
    'Click here to purchase Activation code.',

    //home-popup
    'Notification',
    'Language',
    'Logout',

    //dreamlist
    'Dreams',
    'My Dreams',
    'Suggested Dreams',
    'Suggested dreams not found',
    'Pick This Dream',
    'My dream not found',
    'Date yet to select',
    'LifeTime Total',
    'New in last 28 days',
    'New in last 7 Days',
    'Pending Action',
    'Trust',
    'Cancel',
    'Save',

    //guestList
    'Edit Guest Details',
    'Guest Name',
    'Guest Mobile Number',
    'Add Dream',
    'Select Target Date',
    'Choose Category',
    'Choose Sub Category',
    'Dream Name',
    'Add Dream Image',
    'Shoot picture',
    'Pick from gallery',
    'Name can not be empty',
    'Category is required',
    'Sub Category is required',

    //invitation script
    'Invitation Script',
    'Invitation Categories',
    'Please check your Internet connection',
    'Something went wrong',
    'Copied',
    'No Invitation Script Found',
    'Click here to refresh screen to get latest script',
    'Click here to copy this content and paste on various channel to spread it',
    'No Invitation Categories Found',

    //Meeting
    'Meeting Categories',
    'No Meeting Categories Found',
    'No seminar/webinar found',
    'No Seminar found',
    'Speaker',
    'Invite',
    'Info',
    'Date/Time',
    'Venue',
    'Host',
    'Co-Host',
    'Invitation Link',
    'Copy',
    'Seminar Create',
    'Title',
    'Description',
    'Host name',
    'Host Mobile Number',
    'Date',
    'Time',
    'Venue Name',
    'City',
    'Co-Host Name',
    'Co-Host Mobile Number',
    "Trust",
    'Seminar Create',
    'Webinar Create',
    ' is required',
    'Webinar link',

    //Otp
    'we have sent you an OTP',
    'enter the 6 digit OTP sent on',
    'to proceed',
    'Continue',

    //Login
    'Give us your mobile number',
    'we need your mobile number linked to our account',
    'Give us your email id',
    'we need your email id linked to our account',
    'I agree to the',
    'Terms',
    'Condition',
    'India',
    'eg.9999999999',
    'ActivationCode : FGTY1234',
    'Enter ActivationCode',
    'You need to accept terms & condition',
    'Number not registered, Enter ActivationCode.',
    'Email Id not registered, Enter ActivationCode.',
    'Agree',
    'Continue',
    'eg.test@gmail.com',
    'Select Country',
    'Enter Email For Webinar Link',
    // "Enter Email For Webinar Link",

    //Profile
    'Profile Picture',
    'Name',
    'test@gmail.com',
    'Enter Email ID',
    'Date of Birth',
    'Gender',
    'Marital Status',
    'Education Qualification',
    'Enter City Name',
    'City',
    'WT App Code :',
    'save',
    'Work experience (Years)',
    'Current Individual Income (Yearly)',
    'Occupation',
    'The occupation field ',
    'Direct Selling Experience',
    'Select Direct Selling Experience Count',
    'How many years of Direct selling experience ?',
    'How much Team Created ?',
    'Are you sure?',
    'Do you want to exit an App',
    'No',
    'Yes',
    'Update Profile',
    'Personal',
    'Professional',
    'Request Send to Leader',
    'Cancel',
    'ok',
    'Request Status',
    'You have already send a request, your request has been pending.',
    'Mobile Number must be of 13 digit',
    'Mobile Number must be of 10 digit',
    "Mobile Number must be of 4 digit",
    'Mobile number is must be 10 digit long',
    'Enter WT App Code',
    'WT App Code',
    'Send',
    'Raise Request',
    'Raise Request UpLine',
    'Raise Request DownLine',
    'Send your request to your upper level',
    "Send your request to your Down level",
    "Request Down Level",
    "Request Up Level",
    'WT App Code must be of 8 digit',
    "Member Name can't be empty",
    "Anniversary date",
    "Vestige ID",

    'DOB',
    'The Marital Status',
    'Anniversary date',
    'Select your qualification type',
    'City name',
    'The work experience field',
    'The income field ',
    'Field ',

    // Badge
    'My Badge',
    'No Badge Found',
    'Request For Badge',
    'Badge Type',
    "Uploading Image",
    'Upload your performance screenshot here!',
    'Submit',
    'Select an Image',
    'Click here to select respective badge for which criteria has been achieved.',
    'Click here to open your camera to take photo for evidence of completion for selected badge.',
    'Click here to open your gallery if you have already taken an evidence of badge completion and upload it.',
    'Click here to submit your request for this badge – you will be updated once authority approves it.',
    'View Request',
    'Approve',
    'Reject',
    'Retry',
    'No Badge Request Found',
    'History',
    "Please check your Internet connection",
    'Something went wrong.',
    'No User Badge Found',
    'Click here to refresh your screen to get latest history for badge achiever.',
    'Are You Sure Want To Delete?',
    'Last updated',
    'View More',
    'Less',
    'No Notes Found',
    'Click here to search from notes which you have already saved.',
    'Click here to add your business notes.',
    'No FAQS Found',
    'What would you like to share with us ?',
    'The comment field is required',
    'Your thoughts',
    'Select your satisfaction level of services offered by this application by clicking on start.',
    'Click here to submit your feedback.',
    dotenv.env['APP_NAME'],
    'Phone no',
    'Email',
    'Are you sure you want to logout?',
    'N/A',
    'Upgrade to Next Level',
    'Purchase CEP',
    'You will get all benefits of our App',
    'Constant E-learning program can be accessed from here.',
    'Get all details of Seminars and Webinars here.',
    'Add your dreams and see already added dreams here.',
    'See all New added guest here.',
    'You can upgrade yourself from here, you just need to enter Activation code.',
    'Add your notes here for your reference.',
    'Learn through Video, Audio and E-book from experts.',
    'Are you sure you want to exit an app?',
    'Guest List',
    'Please Enter Guest Name.',
    'No Guest Found',
    'Edit',
    'Change Status',
    'Create New Guest',
    'Cancel',
    'Add New Guest',
    'Enter Name',
    'Guest List Search',
    'WhatsApp not found',
    'No Pending Invited Guests Found',
    'Invited For',
    "hostName",
    "hostMobile",
    "date",
    "city",
    "coHostMobile",
    "coHostName",
    "venue",
    "Close",
    'Search Guest. . .',
    'Seminar/Webinar',
    'Meeting Attended',
    'No seminar/webinar data found',
    'No Presentation Guests Found',
    'Start Follow Up',
    'No Follow Up Guests Found',
    'Joined With You',
    'No Close Guests Found',
    'Days to Close',
    'No Not Interested Guests Found',
    'Start Re-Follow Up',
    'Days to Not Interested',
    'Enter Guest Name',
    'Enter Guest Number',
    'New Contact',
    'Contact sync',
    "Invited For",
    "Webinar",
    'Start Auto Follow',
    "Auto Follow Up",
    "ON/OFF",
    'Joined With You',
    "Days to Close",
    "Days to Died",
    "Request",
    "Uploading Image:",
    'Last updated',
    "YES",
    "Are You Sure Want To Delete?",
    'Search your notes here..',
    'Add Notes',
    'Title is required',
    'Description is required',
    "Enter your note",
    "Save",
    'Title',
    'Edit Notes',
    "No Internet Connection",
    'Your internet is still not working. Please try again later.',
    'Check Again',
    "Activity details",
    "Total Discount",
    "Apply Coupon code",
    "Add CouponCode",
    "Add",
    "Enter CouponCode",
    "CouponCode",
    "Discount",
    "Apply",
    "Member Analytics",
    "Member Dream",
    "Member Activity",

    // pending request
    'Pending Request',
    "Reject",
    'Pending not found',

    // Details team dream
    "No Member Dreams Found",

    // TeamDetails
    'Team Members Name',
    "No analytics in this category",
    "No Pending Request Found",

    //EditTeam
    'Update Team',
    'Please Enter Team Name.',
    'Enter Team Name.',
    "Team Name",
    'Members not found',
    "Select at least one team member",

    // BadgeAchieverList
    'Badge Achiever List',
    'NAME',
    'MOBILE NO.',
    "No List Found",

    // App Update
    "App Update Available",
    'Tap back again to exit app',
    'Please update app to enjoy full featured app with more benefits for you.',
    "UPDATE APP",
    'Are you sure?',

    // app maintenance
    'App Maintenance',
    'Maintenance Mode',
    'This app is currently under going maintenance and will be back online shortly, Thank you for your patience.',
    "EXIT APP",

    // master search
    'Search all. . .',
    'Master Search',

    // news
    "No News Found",
    "Click here to refresh your screen to get latest news from authority.",

    // MyTeam
    'No Team Data Found',
    'Click here to create your custom team to get better monitoring.',
    'Create Team',

    // CreateTeam
    'Select Members to add in Team',
    'Please Enter Team Name.',
    'Enter Team Name',
    'Team Name',
    'No Member Data Found',
    'Select at least one team member',
    'Enter Team Name.',
    "No Member Found",

    // Team Request List
    'Team Request',
    'Team Request List',
    'Pending Request',
    'Members Name',

    // Team Analytics
    'Team Analytics',
    'No analytics in this category',
    'Members List',
    'Members not found',

    // Team Activity
    'Team Activity',
    'Members Name',
    'No Team Activity Data Found',
    'presentationGuests',
    'closedGuests',

    // Team Dream
    'Team Dream',
    'No Members Found',

    // Badge Achiever
    'Badge',
    'No Badge Found',

    // Audio tutorial
    'Audio Tutorial',
    "No Audio Tutorial Found",
    'add',
    "Already added in Cart list.",
    'Successfully added in cart list.',

    // Cart
    'My',
    'Cart',
    " is Empty..!!",
    "Are You Sure Want To Delete This Product?",
    'Payment',
    'CHECKOUT',
    'add cart',
    'Apply a Coupon code',
    'View Offers',
    'Enter Coupon Code',
    'Payment Summary',
    'Sub Total',
    'Coupon Discount',
    'Total',

    //learning eBook search
    "Approve",

    // Audio Learning Search
    'Search ..',
    "Purchase",
    "Member Name",

    // News
    'News',

    // Gallery
    'Gallery',
    'Gallery Photos',

    // Inspiration Club
    'Inspiration Club',
    "No Inspiration Club Found",
    "No Inspiration Club Tutorial Found",

    // Testimonials
    'Testimonials',
    'Add +',
    'Add Testimonial',
    'Enter your Text',
    'FAQs ',
    'No FAQS Found',
    'FeedBack',
    'What would you like to share with us ?',
    'Your thoughts',
    "Approval Pending!",
    'Your Request has not been approved by Admin. Wait for Admin response',
    "No Testimonial Found",
    "Click here to refresh screen to get last updated testimonial.",
    "Click here to add your testimonial.",

    // Contact Us
    'Contact Us',
    'Choose Your Language',

    // My Broadcast
    'My Broadcast',
    'No Broadcast Found',

    // Team Broadcast
    'Team Broadcast',
    'Click here to refresh your screen to get latest message sent by you.',
    'Click here to enter your valuable content to route in team.',
    'Click here to initiate your message to broadcast.',
    'abc',
    'Enter some message',
    'Broadcasting',

    // My Activity
    "No Activity Data Found",
    'Closed -',

    // Video Tutorials
    'Video Tutorials',

    // Video Search
    "Free",
    "Requests Status",

    // Ebook
    'EBook',

    // Ebook Details
    "Error opening url file",
    "View PDF",

    // Analytics
    "Analytics",

    // About CEP
    "About CEP",
    'Winning Team was started by Leading Motivational Speaker,Educator,Business Consultant,a Successful Entrepreneur and sucess icon for many Indians Mr.SP Bharill.Its headquarters is in Jaipur and it is operating in many states of India.We aspire to go global in the time to come and serve our associates worldwide Winning teams purpose is to identify the needs and provide business solutions and empowering people to realize their dreams,providing them with the best education to build the long term,sustainable,business with values & principles.Winning team is one of the best education and vocational training companies in India.It provides education,personality development trainings,workshops and seminars.The aim is to inspire and encourages people,making them to realize their true potential to fulfill their dreams.This is one of the major areas in which Winning Team is involved.Winning Team stands for integrity,Commitment,Excellence and Unity.It has been steadfast in adhering to its business values and ethics;as a result,it has earned the trust of people in india.',

    'About Us',
    'Winning Team was started by Leading Motivational Speaker ,Educator,Business Consultant ,a Successful Entrepreneur and success icon for many Indians Mr.SP Bharill.Its headquarters is in Jaipur and it is oprating in many states of india.We aspire to go global in the time to come and serve our associates worldwide.',
    "Winning team's purpose is to identify the needs and provides business solutions and empowering peole to realize their dreams,provding them with the best education to build the long term,sustainable, profitable,duplicatable & biggest independent business with values & principles.",
    "Winning team is one of the best education and vocational traning companies in India.",
    "It provides education ,personality development trainong,workshops and seminars.The aim is to inspire and encourages people,making them to realize their true potential to filfill their dreams.This is one of the major areas in which Winning Team is involves.",
    "Winning Team stands for Intigrity,Commitment,Excellence and Unity.It has been stadfast in adhering to its business values and ethics as a result ,it has earned the trustof people in India.",

    'About Vestige',
    'Vestige Marketing Pvt.Ltd ,wgich started its operations in the year 2004,is a leading direct selling company dealing in world class health and personal care products.Vestige is constantly growing at a phenomenal rate every year.The growth rate in itself speaks volumes about the quality of the products,the marketing plan and the management that has been able to deliver sucha rewarding and sustainable system.',
    "Vestige is constantly expanding its product range to introduce innovative products every year, manufactured at state-of-the-art manufacturing facilities,which are GMP certified.Vestige is an ISO 9001-2015 certified company and believes in offering world class service levels to all its customers.With over 2000+ online and offline sales outlets pan India,one international office  and several distributor centres .Vestige has built  a widespread network of distributors,which is constantly expanding every year.",
    "Vestige believes in empowering its members with the opportunity to lead their lives on their own terms.With the motto of spreading Wellth,i.e. spreading wealth throught wellness,Vestige has continued to enrich the lives of everyone who is a part of the company and those who belives in its products.",

    // Document eBook
    "Error opening url file",

    // Pick Dream
    'Pick Dream',

    // Edit Dream
    'Edit Dream',
    "Name can't be empty",
    'Image Name',
    // Guest Dashboard
    'Are you sure you want to exit?',
    'Short term',
    'Mid term',
    'Long term',
    'See our user’s testimonials from here and you can add your testimonial also.',
    'DreamList',
    'Add your dreams here which you want to achieve in life and you will have suggested dreams also',
    'Get all the latest News here and be up to date.',
    'Add your important notes here and access it whenever you want.',
    'Learn exclusive content with us in form of Video, Audio and Ebooks',

    // cover photo
    "No Gallery Found",
    "Click here to refresh your screen to get latest picture uploaded here.",

    // Add Guest
    "Add Guest",
    "Add Guests",
    "Contacts Not Add",
    'Search',

    // upgrade package
    'Upgrade Package',
    'Upgrade Package Request',
    "Activation Code can't be empty",
    'Enter Activation Code',
    "Activation Code",
    "Don't have any Activation code ? ",
    'Click Here',
    "Submit",
    'The entered Activation code is invalid.',
    "Click here to enter your Activation code.",
    "Click here to submit your Activation code.",
    "click here to purchase Activation code.",

    // MyVestigeList
    "No",
    "Tutorial Found",

    // NO Data Found
    "No Data Found",
    "Refresh",
    "Click here to refresh your screen to get latest message received by seniors.",

    // Activation cod
    "Click here to redeem your code.",

    // purchase Activation code
    "Purchase ActivationCode",
    'Pricing',
    "Activation code pricing is",
    'Select Package to Buy ActivationCode.',
    'Please Enter Quantity ActivationCode.',
    'Enter code qty',
    "ActivationCode qty",
    "Price",
    "Total",
    'Purchase Code',
    'Please Select Package Category.',
    'Select Package',
    'Payment',
    "Ok",
    "Click here for selection of package.",
    "Click here to enter number of units of selected package.",
    "You will see total payable amount here.",
    "Click here to complete your purchase.",

    // Notification
    'Notification',
    "No Notification Found",

    // app language
    'Change Language?',
    'You can change the language anytime through your language settings.',
    'Training Description',
    'Video Training',
    'Audio Training',
    'Reading Training',
    'Thank you for purchase',
    'EBooks',
    'Open PDF',
    'Go to',

    "Company",

    // Quotes
    "Always do your best. What you plant now, you will harvest later.",
    "Become the person who would attract the results you seek.",
    "Don't watch the clock; do what it does. Keep going.",
    "Either run the day or the day runs you.",
    "Quality performance starts with a positive attitude.",
    "The secret of getting ahead is getting started.",
    "Quality performance starts with a positive attitude.",
    "Setting goals is the first step in turning the invisible into the visible.",
    "Your attitude, not your aptitude, will determine your altitude.",
    "Well done is better than well said.",
    "There is always room at the top.",
    "It’s not about having the right opportunities. It’s about handling the opportunities right.",
    "A goal is a dream with a deadline.",
    "Winning isn’t everything, but wanting to win is.",
    "Outstanding people have one thing in common: An absolute sense of mission.",
    "Fall down seven times and stand up eight.",
    "You just can't beat the person who never gives up.",
    "Fortune favors the bold.",
    "I am not a product of my circumstances. I am a product of my decisions.",
    "Leadership belongs to those who take it.",

    //paginate list no data found
    "There was no record based on the details you entered.",
    "No Data Found In",

    "Already selected language!!!",
    "Genealogy",
    "Create New Broadcast",
    "Current UpLine",
    "Enter Broadcast Name",
    'Please Enter Broadcast Name',
    'Create Broadcast',
    'Edit Members Broadcast',
    'Genealogy',
    'WT App Code',
    'WT App Code',
    'Search by WT App Code...',
    'Name: ',
    'Join Date',
    'Package',
    'Sponsor Count',
    'Add Members',
    'From Camera',
    'From Gallery',
    'Set broadcast image',
    "Update",
    'Delete',
    'Edit Team Name',
    'Camera',
    'online',
    'Broadcast list info',
    'Type your message',
    "Today",
    "Yesterday",
    'Create',

    'Connecting',
    'Send your connection to teammate',
    'Connect to Down line',
    'Connect to Up line',
    'Connect',
    'Member code copied',
    'Package Name',
    'Select Payment Type',
    'Enter amount',
    'webinar amount',
    'Amount : ',
    'Payment amount',
    'Payment amount is must be 2 digit',
    "Crown Members",
    "CEP Prime",
    "Select Package From",
    "CEP Prime",
    "Blocked",
    "10 Core Steps",
    "Guest Sharing",
    "Video Gift",
    "Audio Gift",
    "EBook Gift",
    "Member",
    "Gift To ",
    "Gift by ",
    "Member Gift",
    "Gift to Guest",
    "Guest Request List",
    "Guest Gift",
    "My Gifts",

    'Information For Change Up/Down line',
    'You already have connected with upline.',
    'If you want to connect with another upline then whenever he/she will accept your request, exciting upline will be removed. Please make sure you are aware about all this.',
    'You already have connected with Upline. If you want to connect with another upline then whenever he/she will accept your request, exciting upline will be removed. Please make sure you are aware about all this.',
    'Please make sure you are aware about all this.',
    'Are you sure you want to send request.'
  ].toSet().toList();

  static Map<String, Map> fixedTranslatedTexts = {
    'City': {'hi': 'शहर', 'gu': 'શહેર'},
    '${dotenv.env['APP_NAME']}': {'hi': dotenv.env['APP_NAME_HINDI'], 'gu': dotenv.env['APP_NAME_GUJARATI']},
    'Cart': {'hi': 'कार्ट', 'gu': 'કાર્ટ'},
    'My': {'hi': 'मेरा', 'gu': 'મારું'},
    'Constant E-learning program can be accessed from here.': {
      'hi': 'लगातार ई-लर्निंग कार्यक्रम को यहां से एक्सेस किया जा सकता है।',
      'gu': 'સતત ઇ-લર્નિંગ પ્રોગ્રામ અહીંથી પ્રવેશ કરી શકાય છે.'
    },
    'Learn through Video, Audio and E-book from experts.': {
      'hi': 'विशेषज्ञों से वीडियो, ऑडियो और ई-बुक के माध्यम से जानें।',
      'gu': 'નિષ્ણાતો પાસેથી વિડિઓ, ઓડિયો અને ઇ-બુક દ્વારા શીખો.'
    },
    'Are you sure you want to logout?': {
      'hi': 'क्या आप निस्चय ही यह लॉग आउट करना चाहते हैं? ',
      'gu': 'શું તમે ખરેખર લૉગ આઉટ કરવા માંગો છો?',
    },
  };
}
